// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BraintreeController from "./braintree_controller"
application.register("braintree", BraintreeController)

import CommentFormController from "./comment_form_controller"
application.register("comment-form", CommentFormController)

import Comments__MarkdownController from "./comments/markdown_controller"
application.register("comments--markdown", Comments__MarkdownController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import Ui__TagController from "./ui/tag_controller"
application.register("ui--tag", Ui__TagController)

import Users__AvatarController from "./users/avatar_controller"
application.register("users--avatar", Users__AvatarController)
